// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

import java.lang.InterruptedException;
import java.util.concurrent.ExecutionException;

/**
 * A directory whose contents persist across runs.
 */
public class CacheVolume implements IdProvider<CacheID> {
  private QueryContext queryContext;

  private CacheID id;

  /**
   * Empty constructor for JSON-B deserialization
   */
  protected CacheVolume() {
  }

  CacheVolume(QueryContext queryContext) {
    this.queryContext = queryContext;
  }

  /**
   * <p></p>
   */
  public CacheID id() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.id != null) {
      return id;
    }
    QueryContext ctx = this.queryContext.chain("id");
    return ctx.executeQuery(CacheID.class);
  }
}
