// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A global cache volume identifier.
 */
public class CacheID extends Scalar<String> {

    public CacheID(String value) {
        super(value);
    }
}
