// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A unique container identifier. Null designates an empty container (scratch).
 */
public class ContainerID extends Scalar<String> {

    public ContainerID(String value) {
        super(value);
    }
}
