// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A content-addressed directory identifier.
 */
public class DirectoryID extends Scalar<String> {

    public DirectoryID(String value) {
        super(value);
    }
}
