// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

import java.lang.InterruptedException;
import java.lang.String;
import java.util.concurrent.ExecutionException;

/**
 * A simple key value object that represents an environment variable.
 */
public class EnvVariable {
  private QueryContext queryContext;

  private String name;

  private String value;

  /**
   * Empty constructor for JSON-B deserialization
   */
  protected EnvVariable() {
  }

  EnvVariable(QueryContext queryContext) {
    this.queryContext = queryContext;
  }

  /**
   * <p>The environment variable name.</p>
   */
  public String name() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.name != null) {
      return name;
    }
    QueryContext ctx = this.queryContext.chain("name");
    return ctx.executeQuery(String.class);
  }

  /**
   * <p>The environment variable value.</p>
   */
  public String value() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.value != null) {
      return value;
    }
    QueryContext ctx = this.queryContext.chain("value");
    return ctx.executeQuery(String.class);
  }
}
