// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A file identifier.
 */
public class FileID extends Scalar<String> {

    public FileID(String value) {
        super(value);
    }
}
