// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

import java.lang.InterruptedException;
import java.lang.String;
import java.util.concurrent.ExecutionException;

/**
 * An environment variable on the host environment.
 */
public class HostVariable {
  private QueryContext queryContext;

  private String value;

  /**
   * Empty constructor for JSON-B deserialization
   */
  protected HostVariable() {
  }

  HostVariable(QueryContext queryContext) {
    this.queryContext = queryContext;
  }

  /**
   * <p>A secret referencing the value of this variable.</p>
   */
  public Secret secret() {
    QueryContext ctx = this.queryContext.chain("secret");
    return new Secret(ctx);
  }

  /**
   * <p>The value of this variable.</p>
   */
  public String value() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.value != null) {
      return value;
    }
    QueryContext ctx = this.queryContext.chain("value");
    return ctx.executeQuery(String.class);
  }
}
