// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * Compression algorithm to use for image layers
 */
public enum ImageLayerCompression {
  Uncompressed,

  Gzip,

  Zstd,

  EStarGZ
}
