// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * Transport layer network protocol associated to a port.
 */
public enum NetworkProtocol {
  /**
   * TCP (Transmission Control Protocol)
   */
  TCP,

  /**
   * UDP (User Datagram Protocol)
   */
  UDP
}
