// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * The platform config OS and architecture in a Container.<br/><br/>The format is [os]/[platform]/[version] (e.g., "darwin/arm64/v7", "windows/amd64", "linux/arm64").
 */
public class Platform extends Scalar<String> {

    public Platform(String value) {
        super(value);
    }
}
