// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

import java.lang.Integer;
import java.lang.InterruptedException;
import java.lang.String;
import java.util.concurrent.ExecutionException;

/**
 * A port exposed by a container.
 */
public class Port {
  private QueryContext queryContext;

  private String description;

  private Integer port;

  private NetworkProtocol protocol;

  /**
   * Empty constructor for JSON-B deserialization
   */
  protected Port() {
  }

  Port(QueryContext queryContext) {
    this.queryContext = queryContext;
  }

  /**
   * <p>The port description.</p>
   */
  public String description() throws InterruptedException, ExecutionException,
      DaggerQueryException {
    if (this.description != null) {
      return description;
    }
    QueryContext ctx = this.queryContext.chain("description");
    return ctx.executeQuery(String.class);
  }

  /**
   * <p>The port number.</p>
   */
  public Integer port() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.port != null) {
      return port;
    }
    QueryContext ctx = this.queryContext.chain("port");
    return ctx.executeQuery(Integer.class);
  }

  /**
   * <p>The transport layer network protocol.</p>
   */
  public NetworkProtocol protocol() throws InterruptedException, ExecutionException,
      DaggerQueryException {
    if (this.protocol != null) {
      return protocol;
    }
    QueryContext ctx = this.queryContext.chain("protocol");
    return ctx.executeQuery(NetworkProtocol.class);
  }
}
