// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A unique project identifier.
 */
public class ProjectID extends Scalar<String> {

    public ProjectID(String value) {
        super(value);
    }
}
