// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A unique project command identifier.
 */
public class ProjectCommandID extends Scalar<String> {

    public ProjectCommandID(String value) {
        super(value);
    }
}
