// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A unique identifier for a secret.
 */
public class SecretID extends Scalar<String> {

    public SecretID(String value) {
        super(value);
    }
}
