// This class has been generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

import java.lang.InterruptedException;
import java.util.concurrent.ExecutionException;

public class Socket implements IdProvider<SocketID> {
  private QueryContext queryContext;

  private SocketID id;

  /**
   * Empty constructor for JSON-B deserialization
   */
  protected Socket() {
  }

  Socket(QueryContext queryContext) {
    this.queryContext = queryContext;
  }

  /**
   * <p>The content-addressed identifier of the socket.</p>
   */
  public SocketID id() throws InterruptedException, ExecutionException, DaggerQueryException {
    if (this.id != null) {
      return id;
    }
    QueryContext ctx = this.queryContext.chain("id");
    return ctx.executeQuery(SocketID.class);
  }
}
