// Code generated by dagger-java-sdk. DO NOT EDIT.
package org.chelonix.dagger.client;

/**
 * A content-addressed socket identifier.
 */
public class SocketID extends Scalar<String> {

    public SocketID(String value) {
        super(value);
    }
}
