package org.chelonix.dagger.codegen.introspection;

import com.squareup.javapoet.*;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.io.Writer;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

public class EnumVisitor {
    static void visit(Type type, Function<String, Writer> writerProvider) {
        try (Writer writer = writerProvider.apply(String.format("org/chelonix/dagger/client/%s.java", type.getName())))
        {
            TypeSpec.Builder classBuilder = TypeSpec.enumBuilder(Helpers.formatTypeName(type))
                    .addJavadoc(type.getDescription())
                    .addModifiers(Modifier.PUBLIC);

            for (EnumValue enumValue: type.getEnumValues()) {
                TypeSpec.Builder enumTypeBuilder = TypeSpec.anonymousClassBuilder("")
                        .addJavadoc(enumValue.getDescription());
                if (enumValue.isDeprecated()) {
                    enumTypeBuilder.addAnnotation(Deprecated.class);
                }
                classBuilder.addEnumConstant(enumValue.getName(), enumTypeBuilder.build());
            }

            JavaFile javaFile = JavaFile.builder("org.chelonix.dagger.client", classBuilder.build())
                    .build();
            writer.write("// This class has been generated by dagger-java-sdk. DO NOT EDIT.\n");
            javaFile.writeTo(writer);
            javaFile.writeTo(System.out);
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
        }
    }
}
