name: Build dagger-java-sdk

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build-linux:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify

  build-macos:
    if: github.event_name == 'pull_request' || github.event.pull_request.merged == 'true'
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify

